name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test -v ./... 
