name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
        go: ['oldstable', 'stable']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: '${{ matrix.go }}'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install locales-all (Linux only)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y locales-all

      - name: List Locales
        run: |
          locale -a

      - name: Test
        run: |
          go test -v --race ./...
